@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Marina <-- Bob: another authentication Response
Bob --> Marina: another authentication Response
@enduml
